// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yservice.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace y3d.s {

  /// <summary>Holder for reflection information generated from yservice.proto</summary>
  public static partial class YserviceReflection {

    #region Descriptor
    /// <summary>File descriptor for yservice.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static YserviceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg55c2VydmljZS5wcm90bxIDeTNkGgl5M2QucHJvdG8aGWdvb2dsZS9wcm90",
            "b2J1Zi9hbnkucHJvdG8ynAUKBVRvb2xzEjQKDFJlbmFtZU9iamVjdBIQLnkz",
            "ZC5SZW5hbWVQYXJhbRoQLnkzZC5SZXN1bHRSZXBseSIAEjUKC1NhdmVQcm9q",
            "ZWN0EhAueTNkLlByb2plY3RJbmZvGhIueTNkLlJlc3BvbnNlRXZlbnQiABIy",
            "CgpOZXdQcm9qZWN0EhAueTNkLlN0cmluZ1BhcmFtGhAueTNkLlByb2plY3RJ",
            "bmZvIgASMwoLTG9hZFByb2plY3QSEC55M2QuU3RyaW5nUGFyYW0aEC55M2Qu",
            "UHJvamVjdEluZm8iABIqCgZVbndyYXASDC55M2QuRVVud3JhcBoQLnkzZC5S",
            "ZXN1bHRSZXBseSIAEiwKB1BhY2tpbmcSDS55M2QuRVBhY2tpbmcaEC55M2Qu",
            "UmVzdWx0UmVwbHkiABIsCgdMb3dQb2x5Eg0ueTNkLkVMb3dwb2x5GhAueTNk",
            "LlJlc3VsdFJlcGx5IgASLQoKTG9hZFN5c3RlbRIPLnkzZC5FbXB0eVBhcmFt",
            "GgwueTNkLllTeXN0ZW0iABIuCgpTYXZlU3lzdGVtEgwueTNkLllTeXN0ZW0a",
            "EC55M2QuUmVzdWx0UmVwbHkiABIuCgpCYWtlTm9ybWFsEgwueTNkLkVOb3Jt",
            "YWwaEC55M2QuUmVzdWx0UmVwbHkiABI4Cg1NYWtlTm9kZTRFZGl0EhMueTNk",
            "Lk1ha2U0VGVzdFBhcmFtGhAueTNkLlJlc3VsdFJlcGx5IgASPAoNQmF0Y2hP",
            "cHRpbWl6ZRIXLnkzZC5CYXRjaE9wdGltaXplUGFyYW0aEC55M2QuUmVzdWx0",
            "UmVwbHkiABIuCghUZXN0VGVzdBIOLnkzZC5UZXN0UGFyYW0aEC55M2QuUmVz",
            "dWx0UmVwbHkiADJlCgdZQWN0aW9uEiwKCERvQWN0aW9uEgoueTNkLkV2ZW50",
            "GhIueTNkLlJlc3BvbnNlRXZlbnQoARIsCghEb1Vud3JhcBIMLnkzZC5FVW53",
            "cmFwGhIueTNkLlJlc3BvbnNlRXZlbnRCCKoCBXkzZC5zYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::y3d.e.Y3DReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
