// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ymax.proto

#ifndef PROTOBUF_ymax_2eproto__INCLUDED
#define PROTOBUF_ymax_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace yproto {
class Box3;
class Box3DefaultTypeInternal;
Y3D_EXPORT_MACRO extern Box3DefaultTypeInternal _Box3_default_instance_;
class MNMap;
class MNMapDefaultTypeInternal;
Y3D_EXPORT_MACRO extern MNMapDefaultTypeInternal _MNMap_default_instance_;
class NumFaceRange;
class NumFaceRangeDefaultTypeInternal;
Y3D_EXPORT_MACRO extern NumFaceRangeDefaultTypeInternal _NumFaceRange_default_instance_;
class ObjItem;
class ObjItemDefaultTypeInternal;
Y3D_EXPORT_MACRO extern ObjItemDefaultTypeInternal _ObjItem_default_instance_;
class ObjList;
class ObjListDefaultTypeInternal;
Y3D_EXPORT_MACRO extern ObjListDefaultTypeInternal _ObjList_default_instance_;
class Point3;
class Point3DefaultTypeInternal;
Y3D_EXPORT_MACRO extern Point3DefaultTypeInternal _Point3_default_instance_;
}  // namespace yproto

namespace yproto {

namespace protobuf_ymax_2eproto {
// Internal implementation detail -- do not call these.
struct Y3D_EXPORT_MACRO TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void Y3D_EXPORT_MACRO AddDescriptors();
void Y3D_EXPORT_MACRO InitDefaults();
}  // namespace protobuf_ymax_2eproto

// ===================================================================

class Y3D_EXPORT_MACRO NumFaceRange : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:yproto.NumFaceRange) */ {
 public:
  NumFaceRange();
  virtual ~NumFaceRange();

  NumFaceRange(const NumFaceRange& from);

  inline NumFaceRange& operator=(const NumFaceRange& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NumFaceRange& default_instance();

  static inline const NumFaceRange* internal_default_instance() {
    return reinterpret_cast<const NumFaceRange*>(
               &_NumFaceRange_default_instance_);
  }

  void Swap(NumFaceRange* other);

  // implements Message ----------------------------------------------

  inline NumFaceRange* New() const PROTOBUF_FINAL { return New(NULL); }

  NumFaceRange* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NumFaceRange& from);
  void MergeFrom(const NumFaceRange& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NumFaceRange* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 f = 1;
  int f_size() const;
  void clear_f();
  static const int kFFieldNumber = 1;
  ::google::protobuf::int32 f(int index) const;
  void set_f(int index, ::google::protobuf::int32 value);
  void add_f(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      f() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_f();

  // @@protoc_insertion_point(class_scope:yproto.NumFaceRange)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > f_;
  mutable int _f_cached_byte_size_;
  mutable int _cached_size_;
  friend struct Y3D_EXPORT_MACRO protobuf_ymax_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Y3D_EXPORT_MACRO Point3 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:yproto.Point3) */ {
 public:
  Point3();
  virtual ~Point3();

  Point3(const Point3& from);

  inline Point3& operator=(const Point3& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Point3& default_instance();

  static inline const Point3* internal_default_instance() {
    return reinterpret_cast<const Point3*>(
               &_Point3_default_instance_);
  }

  void Swap(Point3* other);

  // implements Message ----------------------------------------------

  inline Point3* New() const PROTOBUF_FINAL { return New(NULL); }

  Point3* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Point3& from);
  void MergeFrom(const Point3& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Point3* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // float x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // float y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // float z = 3;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:yproto.Point3)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  float x_;
  float y_;
  float z_;
  mutable int _cached_size_;
  friend struct Y3D_EXPORT_MACRO protobuf_ymax_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Y3D_EXPORT_MACRO Box3 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:yproto.Box3) */ {
 public:
  Box3();
  virtual ~Box3();

  Box3(const Box3& from);

  inline Box3& operator=(const Box3& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Box3& default_instance();

  static inline const Box3* internal_default_instance() {
    return reinterpret_cast<const Box3*>(
               &_Box3_default_instance_);
  }

  void Swap(Box3* other);

  // implements Message ----------------------------------------------

  inline Box3* New() const PROTOBUF_FINAL { return New(NULL); }

  Box3* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Box3& from);
  void MergeFrom(const Box3& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Box3* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .yproto.Point3 pmin = 1;
  bool has_pmin() const;
  void clear_pmin();
  static const int kPminFieldNumber = 1;
  const ::yproto::Point3& pmin() const;
  ::yproto::Point3* mutable_pmin();
  ::yproto::Point3* release_pmin();
  void set_allocated_pmin(::yproto::Point3* pmin);

  // .yproto.Point3 pmax = 2;
  bool has_pmax() const;
  void clear_pmax();
  static const int kPmaxFieldNumber = 2;
  const ::yproto::Point3& pmax() const;
  ::yproto::Point3* mutable_pmax();
  ::yproto::Point3* release_pmax();
  void set_allocated_pmax(::yproto::Point3* pmax);

  // @@protoc_insertion_point(class_scope:yproto.Box3)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::yproto::Point3* pmin_;
  ::yproto::Point3* pmax_;
  mutable int _cached_size_;
  friend struct Y3D_EXPORT_MACRO protobuf_ymax_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Y3D_EXPORT_MACRO MNMap : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:yproto.MNMap) */ {
 public:
  MNMap();
  virtual ~MNMap();

  MNMap(const MNMap& from);

  inline MNMap& operator=(const MNMap& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MNMap& default_instance();

  static inline const MNMap* internal_default_instance() {
    return reinterpret_cast<const MNMap*>(
               &_MNMap_default_instance_);
  }

  void Swap(MNMap* other);

  // implements Message ----------------------------------------------

  inline MNMap* New() const PROTOBUF_FINAL { return New(NULL); }

  MNMap* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MNMap& from);
  void MergeFrom(const MNMap& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MNMap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 f = 1;
  int f_size() const;
  void clear_f();
  static const int kFFieldNumber = 1;
  ::google::protobuf::int32 f(int index) const;
  void set_f(int index, ::google::protobuf::int32 value);
  void add_f(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      f() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_f();

  // repeated .yproto.Point3 v = 2;
  int v_size() const;
  void clear_v();
  static const int kVFieldNumber = 2;
  const ::yproto::Point3& v(int index) const;
  ::yproto::Point3* mutable_v(int index);
  ::yproto::Point3* add_v();
  ::google::protobuf::RepeatedPtrField< ::yproto::Point3 >*
      mutable_v();
  const ::google::protobuf::RepeatedPtrField< ::yproto::Point3 >&
      v() const;

  // int32 channel = 3;
  void clear_channel();
  static const int kChannelFieldNumber = 3;
  ::google::protobuf::int32 channel() const;
  void set_channel(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:yproto.MNMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > f_;
  mutable int _f_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::yproto::Point3 > v_;
  ::google::protobuf::int32 channel_;
  mutable int _cached_size_;
  friend struct Y3D_EXPORT_MACRO protobuf_ymax_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Y3D_EXPORT_MACRO ObjItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:yproto.ObjItem) */ {
 public:
  ObjItem();
  virtual ~ObjItem();

  ObjItem(const ObjItem& from);

  inline ObjItem& operator=(const ObjItem& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjItem& default_instance();

  static inline const ObjItem* internal_default_instance() {
    return reinterpret_cast<const ObjItem*>(
               &_ObjItem_default_instance_);
  }

  void Swap(ObjItem* other);

  // implements Message ----------------------------------------------

  inline ObjItem* New() const PROTOBUF_FINAL { return New(NULL); }

  ObjItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ObjItem& from);
  void MergeFrom(const ObjItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ObjItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 xref = 6;
  int xref_size() const;
  void clear_xref();
  static const int kXrefFieldNumber = 6;
  ::google::protobuf::int32 xref(int index) const;
  void set_xref(int index, ::google::protobuf::int32 value);
  void add_xref(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      xref() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_xref();

  // string oname = 1;
  void clear_oname();
  static const int kOnameFieldNumber = 1;
  const ::std::string& oname() const;
  void set_oname(const ::std::string& value);
  #if LANG_CXX11
  void set_oname(::std::string&& value);
  #endif
  void set_oname(const char* value);
  void set_oname(const char* value, size_t size);
  ::std::string* mutable_oname();
  ::std::string* release_oname();
  void set_allocated_oname(::std::string* oname);

  // .yproto.Point3 pos = 4;
  bool has_pos() const;
  void clear_pos();
  static const int kPosFieldNumber = 4;
  const ::yproto::Point3& pos() const;
  ::yproto::Point3* mutable_pos();
  ::yproto::Point3* release_pos();
  void set_allocated_pos(::yproto::Point3* pos);

  // .yproto.Box3 bbox = 5;
  bool has_bbox() const;
  void clear_bbox();
  static const int kBboxFieldNumber = 5;
  const ::yproto::Box3& bbox() const;
  ::yproto::Box3* mutable_bbox();
  ::yproto::Box3* release_bbox();
  void set_allocated_bbox(::yproto::Box3* bbox);

  // uint32 idx = 2;
  void clear_idx();
  static const int kIdxFieldNumber = 2;
  ::google::protobuf::uint32 idx() const;
  void set_idx(::google::protobuf::uint32 value);

  // int32 num_faces = 3;
  void clear_num_faces();
  static const int kNumFacesFieldNumber = 3;
  ::google::protobuf::int32 num_faces() const;
  void set_num_faces(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:yproto.ObjItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > xref_;
  mutable int _xref_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr oname_;
  ::yproto::Point3* pos_;
  ::yproto::Box3* bbox_;
  ::google::protobuf::uint32 idx_;
  ::google::protobuf::int32 num_faces_;
  mutable int _cached_size_;
  friend struct Y3D_EXPORT_MACRO protobuf_ymax_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Y3D_EXPORT_MACRO ObjList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:yproto.ObjList) */ {
 public:
  ObjList();
  virtual ~ObjList();

  ObjList(const ObjList& from);

  inline ObjList& operator=(const ObjList& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjList& default_instance();

  static inline const ObjList* internal_default_instance() {
    return reinterpret_cast<const ObjList*>(
               &_ObjList_default_instance_);
  }

  void Swap(ObjList* other);

  // implements Message ----------------------------------------------

  inline ObjList* New() const PROTOBUF_FINAL { return New(NULL); }

  ObjList* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ObjList& from);
  void MergeFrom(const ObjList& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ObjList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .yproto.ObjItem objs = 1;
  int objs_size() const;
  void clear_objs();
  static const int kObjsFieldNumber = 1;
  const ::yproto::ObjItem& objs(int index) const;
  ::yproto::ObjItem* mutable_objs(int index);
  ::yproto::ObjItem* add_objs();
  ::google::protobuf::RepeatedPtrField< ::yproto::ObjItem >*
      mutable_objs();
  const ::google::protobuf::RepeatedPtrField< ::yproto::ObjItem >&
      objs() const;

  // @@protoc_insertion_point(class_scope:yproto.ObjList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::yproto::ObjItem > objs_;
  mutable int _cached_size_;
  friend struct Y3D_EXPORT_MACRO protobuf_ymax_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// NumFaceRange

// repeated int32 f = 1;
inline int NumFaceRange::f_size() const {
  return f_.size();
}
inline void NumFaceRange::clear_f() {
  f_.Clear();
}
inline ::google::protobuf::int32 NumFaceRange::f(int index) const {
  // @@protoc_insertion_point(field_get:yproto.NumFaceRange.f)
  return f_.Get(index);
}
inline void NumFaceRange::set_f(int index, ::google::protobuf::int32 value) {
  f_.Set(index, value);
  // @@protoc_insertion_point(field_set:yproto.NumFaceRange.f)
}
inline void NumFaceRange::add_f(::google::protobuf::int32 value) {
  f_.Add(value);
  // @@protoc_insertion_point(field_add:yproto.NumFaceRange.f)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
NumFaceRange::f() const {
  // @@protoc_insertion_point(field_list:yproto.NumFaceRange.f)
  return f_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
NumFaceRange::mutable_f() {
  // @@protoc_insertion_point(field_mutable_list:yproto.NumFaceRange.f)
  return &f_;
}

// -------------------------------------------------------------------

// Point3

// float x = 1;
inline void Point3::clear_x() {
  x_ = 0;
}
inline float Point3::x() const {
  // @@protoc_insertion_point(field_get:yproto.Point3.x)
  return x_;
}
inline void Point3::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:yproto.Point3.x)
}

// float y = 2;
inline void Point3::clear_y() {
  y_ = 0;
}
inline float Point3::y() const {
  // @@protoc_insertion_point(field_get:yproto.Point3.y)
  return y_;
}
inline void Point3::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:yproto.Point3.y)
}

// float z = 3;
inline void Point3::clear_z() {
  z_ = 0;
}
inline float Point3::z() const {
  // @@protoc_insertion_point(field_get:yproto.Point3.z)
  return z_;
}
inline void Point3::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:yproto.Point3.z)
}

// -------------------------------------------------------------------

// Box3

// .yproto.Point3 pmin = 1;
inline bool Box3::has_pmin() const {
  return this != internal_default_instance() && pmin_ != NULL;
}
inline void Box3::clear_pmin() {
  if (GetArenaNoVirtual() == NULL && pmin_ != NULL) delete pmin_;
  pmin_ = NULL;
}
inline const ::yproto::Point3& Box3::pmin() const {
  // @@protoc_insertion_point(field_get:yproto.Box3.pmin)
  return pmin_ != NULL ? *pmin_
                         : *::yproto::Point3::internal_default_instance();
}
inline ::yproto::Point3* Box3::mutable_pmin() {
  
  if (pmin_ == NULL) {
    pmin_ = new ::yproto::Point3;
  }
  // @@protoc_insertion_point(field_mutable:yproto.Box3.pmin)
  return pmin_;
}
inline ::yproto::Point3* Box3::release_pmin() {
  // @@protoc_insertion_point(field_release:yproto.Box3.pmin)
  
  ::yproto::Point3* temp = pmin_;
  pmin_ = NULL;
  return temp;
}
inline void Box3::set_allocated_pmin(::yproto::Point3* pmin) {
  delete pmin_;
  pmin_ = pmin;
  if (pmin) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:yproto.Box3.pmin)
}

// .yproto.Point3 pmax = 2;
inline bool Box3::has_pmax() const {
  return this != internal_default_instance() && pmax_ != NULL;
}
inline void Box3::clear_pmax() {
  if (GetArenaNoVirtual() == NULL && pmax_ != NULL) delete pmax_;
  pmax_ = NULL;
}
inline const ::yproto::Point3& Box3::pmax() const {
  // @@protoc_insertion_point(field_get:yproto.Box3.pmax)
  return pmax_ != NULL ? *pmax_
                         : *::yproto::Point3::internal_default_instance();
}
inline ::yproto::Point3* Box3::mutable_pmax() {
  
  if (pmax_ == NULL) {
    pmax_ = new ::yproto::Point3;
  }
  // @@protoc_insertion_point(field_mutable:yproto.Box3.pmax)
  return pmax_;
}
inline ::yproto::Point3* Box3::release_pmax() {
  // @@protoc_insertion_point(field_release:yproto.Box3.pmax)
  
  ::yproto::Point3* temp = pmax_;
  pmax_ = NULL;
  return temp;
}
inline void Box3::set_allocated_pmax(::yproto::Point3* pmax) {
  delete pmax_;
  pmax_ = pmax;
  if (pmax) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:yproto.Box3.pmax)
}

// -------------------------------------------------------------------

// MNMap

// repeated int32 f = 1;
inline int MNMap::f_size() const {
  return f_.size();
}
inline void MNMap::clear_f() {
  f_.Clear();
}
inline ::google::protobuf::int32 MNMap::f(int index) const {
  // @@protoc_insertion_point(field_get:yproto.MNMap.f)
  return f_.Get(index);
}
inline void MNMap::set_f(int index, ::google::protobuf::int32 value) {
  f_.Set(index, value);
  // @@protoc_insertion_point(field_set:yproto.MNMap.f)
}
inline void MNMap::add_f(::google::protobuf::int32 value) {
  f_.Add(value);
  // @@protoc_insertion_point(field_add:yproto.MNMap.f)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
MNMap::f() const {
  // @@protoc_insertion_point(field_list:yproto.MNMap.f)
  return f_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
MNMap::mutable_f() {
  // @@protoc_insertion_point(field_mutable_list:yproto.MNMap.f)
  return &f_;
}

// repeated .yproto.Point3 v = 2;
inline int MNMap::v_size() const {
  return v_.size();
}
inline void MNMap::clear_v() {
  v_.Clear();
}
inline const ::yproto::Point3& MNMap::v(int index) const {
  // @@protoc_insertion_point(field_get:yproto.MNMap.v)
  return v_.Get(index);
}
inline ::yproto::Point3* MNMap::mutable_v(int index) {
  // @@protoc_insertion_point(field_mutable:yproto.MNMap.v)
  return v_.Mutable(index);
}
inline ::yproto::Point3* MNMap::add_v() {
  // @@protoc_insertion_point(field_add:yproto.MNMap.v)
  return v_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::yproto::Point3 >*
MNMap::mutable_v() {
  // @@protoc_insertion_point(field_mutable_list:yproto.MNMap.v)
  return &v_;
}
inline const ::google::protobuf::RepeatedPtrField< ::yproto::Point3 >&
MNMap::v() const {
  // @@protoc_insertion_point(field_list:yproto.MNMap.v)
  return v_;
}

// int32 channel = 3;
inline void MNMap::clear_channel() {
  channel_ = 0;
}
inline ::google::protobuf::int32 MNMap::channel() const {
  // @@protoc_insertion_point(field_get:yproto.MNMap.channel)
  return channel_;
}
inline void MNMap::set_channel(::google::protobuf::int32 value) {
  
  channel_ = value;
  // @@protoc_insertion_point(field_set:yproto.MNMap.channel)
}

// -------------------------------------------------------------------

// ObjItem

// string oname = 1;
inline void ObjItem::clear_oname() {
  oname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ObjItem::oname() const {
  // @@protoc_insertion_point(field_get:yproto.ObjItem.oname)
  return oname_.GetNoArena();
}
inline void ObjItem::set_oname(const ::std::string& value) {
  
  oname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yproto.ObjItem.oname)
}
#if LANG_CXX11
inline void ObjItem::set_oname(::std::string&& value) {
  
  oname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:yproto.ObjItem.oname)
}
#endif
inline void ObjItem::set_oname(const char* value) {
  
  oname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yproto.ObjItem.oname)
}
inline void ObjItem::set_oname(const char* value, size_t size) {
  
  oname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yproto.ObjItem.oname)
}
inline ::std::string* ObjItem::mutable_oname() {
  
  // @@protoc_insertion_point(field_mutable:yproto.ObjItem.oname)
  return oname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ObjItem::release_oname() {
  // @@protoc_insertion_point(field_release:yproto.ObjItem.oname)
  
  return oname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ObjItem::set_allocated_oname(::std::string* oname) {
  if (oname != NULL) {
    
  } else {
    
  }
  oname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), oname);
  // @@protoc_insertion_point(field_set_allocated:yproto.ObjItem.oname)
}

// uint32 idx = 2;
inline void ObjItem::clear_idx() {
  idx_ = 0u;
}
inline ::google::protobuf::uint32 ObjItem::idx() const {
  // @@protoc_insertion_point(field_get:yproto.ObjItem.idx)
  return idx_;
}
inline void ObjItem::set_idx(::google::protobuf::uint32 value) {
  
  idx_ = value;
  // @@protoc_insertion_point(field_set:yproto.ObjItem.idx)
}

// int32 num_faces = 3;
inline void ObjItem::clear_num_faces() {
  num_faces_ = 0;
}
inline ::google::protobuf::int32 ObjItem::num_faces() const {
  // @@protoc_insertion_point(field_get:yproto.ObjItem.num_faces)
  return num_faces_;
}
inline void ObjItem::set_num_faces(::google::protobuf::int32 value) {
  
  num_faces_ = value;
  // @@protoc_insertion_point(field_set:yproto.ObjItem.num_faces)
}

// .yproto.Point3 pos = 4;
inline bool ObjItem::has_pos() const {
  return this != internal_default_instance() && pos_ != NULL;
}
inline void ObjItem::clear_pos() {
  if (GetArenaNoVirtual() == NULL && pos_ != NULL) delete pos_;
  pos_ = NULL;
}
inline const ::yproto::Point3& ObjItem::pos() const {
  // @@protoc_insertion_point(field_get:yproto.ObjItem.pos)
  return pos_ != NULL ? *pos_
                         : *::yproto::Point3::internal_default_instance();
}
inline ::yproto::Point3* ObjItem::mutable_pos() {
  
  if (pos_ == NULL) {
    pos_ = new ::yproto::Point3;
  }
  // @@protoc_insertion_point(field_mutable:yproto.ObjItem.pos)
  return pos_;
}
inline ::yproto::Point3* ObjItem::release_pos() {
  // @@protoc_insertion_point(field_release:yproto.ObjItem.pos)
  
  ::yproto::Point3* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline void ObjItem::set_allocated_pos(::yproto::Point3* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:yproto.ObjItem.pos)
}

// .yproto.Box3 bbox = 5;
inline bool ObjItem::has_bbox() const {
  return this != internal_default_instance() && bbox_ != NULL;
}
inline void ObjItem::clear_bbox() {
  if (GetArenaNoVirtual() == NULL && bbox_ != NULL) delete bbox_;
  bbox_ = NULL;
}
inline const ::yproto::Box3& ObjItem::bbox() const {
  // @@protoc_insertion_point(field_get:yproto.ObjItem.bbox)
  return bbox_ != NULL ? *bbox_
                         : *::yproto::Box3::internal_default_instance();
}
inline ::yproto::Box3* ObjItem::mutable_bbox() {
  
  if (bbox_ == NULL) {
    bbox_ = new ::yproto::Box3;
  }
  // @@protoc_insertion_point(field_mutable:yproto.ObjItem.bbox)
  return bbox_;
}
inline ::yproto::Box3* ObjItem::release_bbox() {
  // @@protoc_insertion_point(field_release:yproto.ObjItem.bbox)
  
  ::yproto::Box3* temp = bbox_;
  bbox_ = NULL;
  return temp;
}
inline void ObjItem::set_allocated_bbox(::yproto::Box3* bbox) {
  delete bbox_;
  bbox_ = bbox;
  if (bbox) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:yproto.ObjItem.bbox)
}

// repeated int32 xref = 6;
inline int ObjItem::xref_size() const {
  return xref_.size();
}
inline void ObjItem::clear_xref() {
  xref_.Clear();
}
inline ::google::protobuf::int32 ObjItem::xref(int index) const {
  // @@protoc_insertion_point(field_get:yproto.ObjItem.xref)
  return xref_.Get(index);
}
inline void ObjItem::set_xref(int index, ::google::protobuf::int32 value) {
  xref_.Set(index, value);
  // @@protoc_insertion_point(field_set:yproto.ObjItem.xref)
}
inline void ObjItem::add_xref(::google::protobuf::int32 value) {
  xref_.Add(value);
  // @@protoc_insertion_point(field_add:yproto.ObjItem.xref)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ObjItem::xref() const {
  // @@protoc_insertion_point(field_list:yproto.ObjItem.xref)
  return xref_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ObjItem::mutable_xref() {
  // @@protoc_insertion_point(field_mutable_list:yproto.ObjItem.xref)
  return &xref_;
}

// -------------------------------------------------------------------

// ObjList

// repeated .yproto.ObjItem objs = 1;
inline int ObjList::objs_size() const {
  return objs_.size();
}
inline void ObjList::clear_objs() {
  objs_.Clear();
}
inline const ::yproto::ObjItem& ObjList::objs(int index) const {
  // @@protoc_insertion_point(field_get:yproto.ObjList.objs)
  return objs_.Get(index);
}
inline ::yproto::ObjItem* ObjList::mutable_objs(int index) {
  // @@protoc_insertion_point(field_mutable:yproto.ObjList.objs)
  return objs_.Mutable(index);
}
inline ::yproto::ObjItem* ObjList::add_objs() {
  // @@protoc_insertion_point(field_add:yproto.ObjList.objs)
  return objs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::yproto::ObjItem >*
ObjList::mutable_objs() {
  // @@protoc_insertion_point(field_mutable_list:yproto.ObjList.objs)
  return &objs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::yproto::ObjItem >&
ObjList::objs() const {
  // @@protoc_insertion_point(field_list:yproto.ObjList.objs)
  return objs_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace yproto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ymax_2eproto__INCLUDED
