// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ymax.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ymax.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace yproto {

namespace {

const ::google::protobuf::Descriptor* NumFaceRange_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  NumFaceRange_reflection_ = NULL;
const ::google::protobuf::Descriptor* Point3_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Point3_reflection_ = NULL;
const ::google::protobuf::Descriptor* Box3_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Box3_reflection_ = NULL;
const ::google::protobuf::Descriptor* MNMap_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MNMap_reflection_ = NULL;
const ::google::protobuf::Descriptor* ObjItem_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ObjItem_reflection_ = NULL;
const ::google::protobuf::Descriptor* ObjList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ObjList_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ymax_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_ymax_2eproto() {
  protobuf_AddDesc_ymax_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ymax.proto");
  GOOGLE_CHECK(file != NULL);
  NumFaceRange_descriptor_ = file->message_type(0);
  static const int NumFaceRange_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NumFaceRange, f_),
  };
  NumFaceRange_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      NumFaceRange_descriptor_,
      NumFaceRange::default_instance_,
      NumFaceRange_offsets_,
      -1,
      -1,
      -1,
      sizeof(NumFaceRange),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NumFaceRange, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NumFaceRange, _is_default_instance_));
  Point3_descriptor_ = file->message_type(1);
  static const int Point3_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Point3, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Point3, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Point3, z_),
  };
  Point3_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Point3_descriptor_,
      Point3::default_instance_,
      Point3_offsets_,
      -1,
      -1,
      -1,
      sizeof(Point3),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Point3, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Point3, _is_default_instance_));
  Box3_descriptor_ = file->message_type(2);
  static const int Box3_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Box3, pmin_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Box3, pmax_),
  };
  Box3_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Box3_descriptor_,
      Box3::default_instance_,
      Box3_offsets_,
      -1,
      -1,
      -1,
      sizeof(Box3),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Box3, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Box3, _is_default_instance_));
  MNMap_descriptor_ = file->message_type(3);
  static const int MNMap_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MNMap, f_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MNMap, v_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MNMap, channel_),
  };
  MNMap_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MNMap_descriptor_,
      MNMap::default_instance_,
      MNMap_offsets_,
      -1,
      -1,
      -1,
      sizeof(MNMap),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MNMap, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MNMap, _is_default_instance_));
  ObjItem_descriptor_ = file->message_type(4);
  static const int ObjItem_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjItem, oname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjItem, idx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjItem, num_faces_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjItem, pos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjItem, bbox_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjItem, xref_),
  };
  ObjItem_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ObjItem_descriptor_,
      ObjItem::default_instance_,
      ObjItem_offsets_,
      -1,
      -1,
      -1,
      sizeof(ObjItem),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjItem, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjItem, _is_default_instance_));
  ObjList_descriptor_ = file->message_type(5);
  static const int ObjList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjList, objs_),
  };
  ObjList_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ObjList_descriptor_,
      ObjList::default_instance_,
      ObjList_offsets_,
      -1,
      -1,
      -1,
      sizeof(ObjList),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjList, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjList, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ymax_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      NumFaceRange_descriptor_, &NumFaceRange::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Point3_descriptor_, &Point3::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Box3_descriptor_, &Box3::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MNMap_descriptor_, &MNMap::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ObjItem_descriptor_, &ObjItem::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ObjList_descriptor_, &ObjList::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ymax_2eproto() {
  delete NumFaceRange::default_instance_;
  delete NumFaceRange_reflection_;
  delete Point3::default_instance_;
  delete Point3_reflection_;
  delete Box3::default_instance_;
  delete Box3_reflection_;
  delete MNMap::default_instance_;
  delete MNMap_reflection_;
  delete ObjItem::default_instance_;
  delete ObjItem_reflection_;
  delete ObjList::default_instance_;
  delete ObjList_reflection_;
}

void protobuf_AddDesc_ymax_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_ymax_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nymax.proto\022\006yproto\"\031\n\014NumFaceRange\022\t\n\001"
    "f\030\001 \003(\005\")\n\006Point3\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022"
    "\t\n\001z\030\003 \001(\002\"B\n\004Box3\022\034\n\004pmin\030\001 \001(\0132\016.yprot"
    "o.Point3\022\034\n\004pmax\030\002 \001(\0132\016.yproto.Point3\">"
    "\n\005MNMap\022\t\n\001f\030\001 \003(\005\022\031\n\001v\030\002 \003(\0132\016.yproto.P"
    "oint3\022\017\n\007channel\030\003 \001(\005\"\177\n\007ObjItem\022\r\n\005ona"
    "me\030\001 \001(\t\022\013\n\003idx\030\002 \001(\r\022\021\n\tnum_faces\030\003 \001(\005"
    "\022\033\n\003pos\030\004 \001(\0132\016.yproto.Point3\022\032\n\004bbox\030\005 "
    "\001(\0132\014.yproto.Box3\022\014\n\004xref\030\006 \003(\005\"(\n\007ObjLi"
    "st\022\035\n\004objs\030\001 \003(\0132\017.yproto.ObjItem2>\n\010YPr"
    "epare\0222\n\007MakeBox\022\024.yproto.NumFaceRange\032\017"
    ".yproto.ObjList\"\000B\017\242\002\003Y3D\252\002\006yprotob\006prot"
    "o3", 482);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ymax.proto", &protobuf_RegisterTypes);
  NumFaceRange::default_instance_ = new NumFaceRange();
  Point3::default_instance_ = new Point3();
  Box3::default_instance_ = new Box3();
  MNMap::default_instance_ = new MNMap();
  ObjItem::default_instance_ = new ObjItem();
  ObjList::default_instance_ = new ObjList();
  NumFaceRange::default_instance_->InitAsDefaultInstance();
  Point3::default_instance_->InitAsDefaultInstance();
  Box3::default_instance_->InitAsDefaultInstance();
  MNMap::default_instance_->InitAsDefaultInstance();
  ObjItem::default_instance_->InitAsDefaultInstance();
  ObjList::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ymax_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ymax_2eproto {
  StaticDescriptorInitializer_ymax_2eproto() {
    protobuf_AddDesc_ymax_2eproto();
  }
} static_descriptor_initializer_ymax_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NumFaceRange::kFFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NumFaceRange::NumFaceRange()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yproto.NumFaceRange)
}

void NumFaceRange::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

NumFaceRange::NumFaceRange(const NumFaceRange& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yproto.NumFaceRange)
}

void NumFaceRange::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

NumFaceRange::~NumFaceRange() {
  // @@protoc_insertion_point(destructor:yproto.NumFaceRange)
  SharedDtor();
}

void NumFaceRange::SharedDtor() {
  if (this != default_instance_) {
  }
}

void NumFaceRange::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NumFaceRange::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NumFaceRange_descriptor_;
}

const NumFaceRange& NumFaceRange::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ymax_2eproto();
  return *default_instance_;
}

NumFaceRange* NumFaceRange::default_instance_ = NULL;

NumFaceRange* NumFaceRange::New(::google::protobuf::Arena* arena) const {
  NumFaceRange* n = new NumFaceRange;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NumFaceRange::Clear() {
// @@protoc_insertion_point(message_clear_start:yproto.NumFaceRange)
  f_.Clear();
}

bool NumFaceRange::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yproto.NumFaceRange)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 f = 1;
      case 1: {
        if (tag == 10) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_f())));
        } else if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 10, input, this->mutable_f())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yproto.NumFaceRange)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yproto.NumFaceRange)
  return false;
#undef DO_
}

void NumFaceRange::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yproto.NumFaceRange)
  // repeated int32 f = 1;
  if (this->f_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_f_cached_byte_size_);
  }
  for (int i = 0; i < this->f_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->f(i), output);
  }

  // @@protoc_insertion_point(serialize_end:yproto.NumFaceRange)
}

::google::protobuf::uint8* NumFaceRange::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:yproto.NumFaceRange)
  // repeated int32 f = 1;
  if (this->f_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _f_cached_byte_size_, target);
  }
  for (int i = 0; i < this->f_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->f(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:yproto.NumFaceRange)
  return target;
}

int NumFaceRange::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yproto.NumFaceRange)
  int total_size = 0;

  // repeated int32 f = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->f_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->f(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _f_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NumFaceRange::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yproto.NumFaceRange)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const NumFaceRange* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const NumFaceRange>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yproto.NumFaceRange)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yproto.NumFaceRange)
    MergeFrom(*source);
  }
}

void NumFaceRange::MergeFrom(const NumFaceRange& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yproto.NumFaceRange)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  f_.MergeFrom(from.f_);
}

void NumFaceRange::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yproto.NumFaceRange)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NumFaceRange::CopyFrom(const NumFaceRange& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yproto.NumFaceRange)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NumFaceRange::IsInitialized() const {

  return true;
}

void NumFaceRange::Swap(NumFaceRange* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NumFaceRange::InternalSwap(NumFaceRange* other) {
  f_.UnsafeArenaSwap(&other->f_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata NumFaceRange::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = NumFaceRange_descriptor_;
  metadata.reflection = NumFaceRange_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// NumFaceRange

// repeated int32 f = 1;
int NumFaceRange::f_size() const {
  return f_.size();
}
void NumFaceRange::clear_f() {
  f_.Clear();
}
 ::google::protobuf::int32 NumFaceRange::f(int index) const {
  // @@protoc_insertion_point(field_get:yproto.NumFaceRange.f)
  return f_.Get(index);
}
 void NumFaceRange::set_f(int index, ::google::protobuf::int32 value) {
  f_.Set(index, value);
  // @@protoc_insertion_point(field_set:yproto.NumFaceRange.f)
}
 void NumFaceRange::add_f(::google::protobuf::int32 value) {
  f_.Add(value);
  // @@protoc_insertion_point(field_add:yproto.NumFaceRange.f)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
NumFaceRange::f() const {
  // @@protoc_insertion_point(field_list:yproto.NumFaceRange.f)
  return f_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
NumFaceRange::mutable_f() {
  // @@protoc_insertion_point(field_mutable_list:yproto.NumFaceRange.f)
  return &f_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Point3::kXFieldNumber;
const int Point3::kYFieldNumber;
const int Point3::kZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Point3::Point3()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yproto.Point3)
}

void Point3::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Point3::Point3(const Point3& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yproto.Point3)
}

void Point3::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
  z_ = 0;
}

Point3::~Point3() {
  // @@protoc_insertion_point(destructor:yproto.Point3)
  SharedDtor();
}

void Point3::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Point3::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Point3::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Point3_descriptor_;
}

const Point3& Point3::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ymax_2eproto();
  return *default_instance_;
}

Point3* Point3::default_instance_ = NULL;

Point3* Point3::New(::google::protobuf::Arena* arena) const {
  Point3* n = new Point3;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Point3::Clear() {
// @@protoc_insertion_point(message_clear_start:yproto.Point3)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Point3, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Point3*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(x_, z_);

#undef ZR_HELPER_
#undef ZR_

}

bool Point3::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yproto.Point3)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float x = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_y;
        break;
      }

      // optional float y = 2;
      case 2: {
        if (tag == 21) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_z;
        break;
      }

      // optional float z = 3;
      case 3: {
        if (tag == 29) {
         parse_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yproto.Point3)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yproto.Point3)
  return false;
#undef DO_
}

void Point3::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yproto.Point3)
  // optional float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // optional float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  // optional float z = 3;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->z(), output);
  }

  // @@protoc_insertion_point(serialize_end:yproto.Point3)
}

::google::protobuf::uint8* Point3::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:yproto.Point3)
  // optional float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // optional float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  // optional float z = 3;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->z(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:yproto.Point3)
  return target;
}

int Point3::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yproto.Point3)
  int total_size = 0;

  // optional float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // optional float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // optional float z = 3;
  if (this->z() != 0) {
    total_size += 1 + 4;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Point3::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yproto.Point3)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Point3* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Point3>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yproto.Point3)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yproto.Point3)
    MergeFrom(*source);
  }
}

void Point3::MergeFrom(const Point3& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yproto.Point3)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
}

void Point3::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yproto.Point3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Point3::CopyFrom(const Point3& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yproto.Point3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Point3::IsInitialized() const {

  return true;
}

void Point3::Swap(Point3* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Point3::InternalSwap(Point3* other) {
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(z_, other->z_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Point3::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Point3_descriptor_;
  metadata.reflection = Point3_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Point3

// optional float x = 1;
void Point3::clear_x() {
  x_ = 0;
}
 float Point3::x() const {
  // @@protoc_insertion_point(field_get:yproto.Point3.x)
  return x_;
}
 void Point3::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:yproto.Point3.x)
}

// optional float y = 2;
void Point3::clear_y() {
  y_ = 0;
}
 float Point3::y() const {
  // @@protoc_insertion_point(field_get:yproto.Point3.y)
  return y_;
}
 void Point3::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:yproto.Point3.y)
}

// optional float z = 3;
void Point3::clear_z() {
  z_ = 0;
}
 float Point3::z() const {
  // @@protoc_insertion_point(field_get:yproto.Point3.z)
  return z_;
}
 void Point3::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:yproto.Point3.z)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Box3::kPminFieldNumber;
const int Box3::kPmaxFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Box3::Box3()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yproto.Box3)
}

void Box3::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  pmin_ = const_cast< ::yproto::Point3*>(&::yproto::Point3::default_instance());
  pmax_ = const_cast< ::yproto::Point3*>(&::yproto::Point3::default_instance());
}

Box3::Box3(const Box3& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yproto.Box3)
}

void Box3::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  pmin_ = NULL;
  pmax_ = NULL;
}

Box3::~Box3() {
  // @@protoc_insertion_point(destructor:yproto.Box3)
  SharedDtor();
}

void Box3::SharedDtor() {
  if (this != default_instance_) {
    delete pmin_;
    delete pmax_;
  }
}

void Box3::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Box3::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Box3_descriptor_;
}

const Box3& Box3::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ymax_2eproto();
  return *default_instance_;
}

Box3* Box3::default_instance_ = NULL;

Box3* Box3::New(::google::protobuf::Arena* arena) const {
  Box3* n = new Box3;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Box3::Clear() {
// @@protoc_insertion_point(message_clear_start:yproto.Box3)
  if (GetArenaNoVirtual() == NULL && pmin_ != NULL) delete pmin_;
  pmin_ = NULL;
  if (GetArenaNoVirtual() == NULL && pmax_ != NULL) delete pmax_;
  pmax_ = NULL;
}

bool Box3::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yproto.Box3)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .yproto.Point3 pmin = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_pmin()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_pmax;
        break;
      }

      // optional .yproto.Point3 pmax = 2;
      case 2: {
        if (tag == 18) {
         parse_pmax:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_pmax()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yproto.Box3)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yproto.Box3)
  return false;
#undef DO_
}

void Box3::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yproto.Box3)
  // optional .yproto.Point3 pmin = 1;
  if (this->has_pmin()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->pmin_, output);
  }

  // optional .yproto.Point3 pmax = 2;
  if (this->has_pmax()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->pmax_, output);
  }

  // @@protoc_insertion_point(serialize_end:yproto.Box3)
}

::google::protobuf::uint8* Box3::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:yproto.Box3)
  // optional .yproto.Point3 pmin = 1;
  if (this->has_pmin()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->pmin_, false, target);
  }

  // optional .yproto.Point3 pmax = 2;
  if (this->has_pmax()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->pmax_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:yproto.Box3)
  return target;
}

int Box3::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yproto.Box3)
  int total_size = 0;

  // optional .yproto.Point3 pmin = 1;
  if (this->has_pmin()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->pmin_);
  }

  // optional .yproto.Point3 pmax = 2;
  if (this->has_pmax()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->pmax_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Box3::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yproto.Box3)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Box3* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Box3>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yproto.Box3)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yproto.Box3)
    MergeFrom(*source);
  }
}

void Box3::MergeFrom(const Box3& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yproto.Box3)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.has_pmin()) {
    mutable_pmin()->::yproto::Point3::MergeFrom(from.pmin());
  }
  if (from.has_pmax()) {
    mutable_pmax()->::yproto::Point3::MergeFrom(from.pmax());
  }
}

void Box3::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yproto.Box3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Box3::CopyFrom(const Box3& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yproto.Box3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Box3::IsInitialized() const {

  return true;
}

void Box3::Swap(Box3* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Box3::InternalSwap(Box3* other) {
  std::swap(pmin_, other->pmin_);
  std::swap(pmax_, other->pmax_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Box3::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Box3_descriptor_;
  metadata.reflection = Box3_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Box3

// optional .yproto.Point3 pmin = 1;
bool Box3::has_pmin() const {
  return !_is_default_instance_ && pmin_ != NULL;
}
void Box3::clear_pmin() {
  if (GetArenaNoVirtual() == NULL && pmin_ != NULL) delete pmin_;
  pmin_ = NULL;
}
const ::yproto::Point3& Box3::pmin() const {
  // @@protoc_insertion_point(field_get:yproto.Box3.pmin)
  return pmin_ != NULL ? *pmin_ : *default_instance_->pmin_;
}
::yproto::Point3* Box3::mutable_pmin() {
  
  if (pmin_ == NULL) {
    pmin_ = new ::yproto::Point3;
  }
  // @@protoc_insertion_point(field_mutable:yproto.Box3.pmin)
  return pmin_;
}
::yproto::Point3* Box3::release_pmin() {
  // @@protoc_insertion_point(field_release:yproto.Box3.pmin)
  
  ::yproto::Point3* temp = pmin_;
  pmin_ = NULL;
  return temp;
}
void Box3::set_allocated_pmin(::yproto::Point3* pmin) {
  delete pmin_;
  pmin_ = pmin;
  if (pmin) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:yproto.Box3.pmin)
}

// optional .yproto.Point3 pmax = 2;
bool Box3::has_pmax() const {
  return !_is_default_instance_ && pmax_ != NULL;
}
void Box3::clear_pmax() {
  if (GetArenaNoVirtual() == NULL && pmax_ != NULL) delete pmax_;
  pmax_ = NULL;
}
const ::yproto::Point3& Box3::pmax() const {
  // @@protoc_insertion_point(field_get:yproto.Box3.pmax)
  return pmax_ != NULL ? *pmax_ : *default_instance_->pmax_;
}
::yproto::Point3* Box3::mutable_pmax() {
  
  if (pmax_ == NULL) {
    pmax_ = new ::yproto::Point3;
  }
  // @@protoc_insertion_point(field_mutable:yproto.Box3.pmax)
  return pmax_;
}
::yproto::Point3* Box3::release_pmax() {
  // @@protoc_insertion_point(field_release:yproto.Box3.pmax)
  
  ::yproto::Point3* temp = pmax_;
  pmax_ = NULL;
  return temp;
}
void Box3::set_allocated_pmax(::yproto::Point3* pmax) {
  delete pmax_;
  pmax_ = pmax;
  if (pmax) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:yproto.Box3.pmax)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MNMap::kFFieldNumber;
const int MNMap::kVFieldNumber;
const int MNMap::kChannelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MNMap::MNMap()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yproto.MNMap)
}

void MNMap::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MNMap::MNMap(const MNMap& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yproto.MNMap)
}

void MNMap::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  channel_ = 0;
}

MNMap::~MNMap() {
  // @@protoc_insertion_point(destructor:yproto.MNMap)
  SharedDtor();
}

void MNMap::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MNMap::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MNMap::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MNMap_descriptor_;
}

const MNMap& MNMap::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ymax_2eproto();
  return *default_instance_;
}

MNMap* MNMap::default_instance_ = NULL;

MNMap* MNMap::New(::google::protobuf::Arena* arena) const {
  MNMap* n = new MNMap;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MNMap::Clear() {
// @@protoc_insertion_point(message_clear_start:yproto.MNMap)
  channel_ = 0;
  f_.Clear();
  v_.Clear();
}

bool MNMap::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yproto.MNMap)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 f = 1;
      case 1: {
        if (tag == 10) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_f())));
        } else if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 10, input, this->mutable_f())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_v;
        break;
      }

      // repeated .yproto.Point3 v = 2;
      case 2: {
        if (tag == 18) {
         parse_v:
          DO_(input->IncrementRecursionDepth());
         parse_loop_v:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_v()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_v;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(24)) goto parse_channel;
        break;
      }

      // optional int32 channel = 3;
      case 3: {
        if (tag == 24) {
         parse_channel:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &channel_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yproto.MNMap)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yproto.MNMap)
  return false;
#undef DO_
}

void MNMap::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yproto.MNMap)
  // repeated int32 f = 1;
  if (this->f_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_f_cached_byte_size_);
  }
  for (int i = 0; i < this->f_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->f(i), output);
  }

  // repeated .yproto.Point3 v = 2;
  for (unsigned int i = 0, n = this->v_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->v(i), output);
  }

  // optional int32 channel = 3;
  if (this->channel() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->channel(), output);
  }

  // @@protoc_insertion_point(serialize_end:yproto.MNMap)
}

::google::protobuf::uint8* MNMap::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:yproto.MNMap)
  // repeated int32 f = 1;
  if (this->f_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _f_cached_byte_size_, target);
  }
  for (int i = 0; i < this->f_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->f(i), target);
  }

  // repeated .yproto.Point3 v = 2;
  for (unsigned int i = 0, n = this->v_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->v(i), false, target);
  }

  // optional int32 channel = 3;
  if (this->channel() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->channel(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:yproto.MNMap)
  return target;
}

int MNMap::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yproto.MNMap)
  int total_size = 0;

  // optional int32 channel = 3;
  if (this->channel() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->channel());
  }

  // repeated int32 f = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->f_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->f(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _f_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated .yproto.Point3 v = 2;
  total_size += 1 * this->v_size();
  for (int i = 0; i < this->v_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->v(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MNMap::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yproto.MNMap)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const MNMap* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MNMap>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yproto.MNMap)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yproto.MNMap)
    MergeFrom(*source);
  }
}

void MNMap::MergeFrom(const MNMap& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yproto.MNMap)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  f_.MergeFrom(from.f_);
  v_.MergeFrom(from.v_);
  if (from.channel() != 0) {
    set_channel(from.channel());
  }
}

void MNMap::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yproto.MNMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MNMap::CopyFrom(const MNMap& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yproto.MNMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MNMap::IsInitialized() const {

  return true;
}

void MNMap::Swap(MNMap* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MNMap::InternalSwap(MNMap* other) {
  f_.UnsafeArenaSwap(&other->f_);
  v_.UnsafeArenaSwap(&other->v_);
  std::swap(channel_, other->channel_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MNMap::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MNMap_descriptor_;
  metadata.reflection = MNMap_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MNMap

// repeated int32 f = 1;
int MNMap::f_size() const {
  return f_.size();
}
void MNMap::clear_f() {
  f_.Clear();
}
 ::google::protobuf::int32 MNMap::f(int index) const {
  // @@protoc_insertion_point(field_get:yproto.MNMap.f)
  return f_.Get(index);
}
 void MNMap::set_f(int index, ::google::protobuf::int32 value) {
  f_.Set(index, value);
  // @@protoc_insertion_point(field_set:yproto.MNMap.f)
}
 void MNMap::add_f(::google::protobuf::int32 value) {
  f_.Add(value);
  // @@protoc_insertion_point(field_add:yproto.MNMap.f)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
MNMap::f() const {
  // @@protoc_insertion_point(field_list:yproto.MNMap.f)
  return f_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
MNMap::mutable_f() {
  // @@protoc_insertion_point(field_mutable_list:yproto.MNMap.f)
  return &f_;
}

// repeated .yproto.Point3 v = 2;
int MNMap::v_size() const {
  return v_.size();
}
void MNMap::clear_v() {
  v_.Clear();
}
const ::yproto::Point3& MNMap::v(int index) const {
  // @@protoc_insertion_point(field_get:yproto.MNMap.v)
  return v_.Get(index);
}
::yproto::Point3* MNMap::mutable_v(int index) {
  // @@protoc_insertion_point(field_mutable:yproto.MNMap.v)
  return v_.Mutable(index);
}
::yproto::Point3* MNMap::add_v() {
  // @@protoc_insertion_point(field_add:yproto.MNMap.v)
  return v_.Add();
}
::google::protobuf::RepeatedPtrField< ::yproto::Point3 >*
MNMap::mutable_v() {
  // @@protoc_insertion_point(field_mutable_list:yproto.MNMap.v)
  return &v_;
}
const ::google::protobuf::RepeatedPtrField< ::yproto::Point3 >&
MNMap::v() const {
  // @@protoc_insertion_point(field_list:yproto.MNMap.v)
  return v_;
}

// optional int32 channel = 3;
void MNMap::clear_channel() {
  channel_ = 0;
}
 ::google::protobuf::int32 MNMap::channel() const {
  // @@protoc_insertion_point(field_get:yproto.MNMap.channel)
  return channel_;
}
 void MNMap::set_channel(::google::protobuf::int32 value) {
  
  channel_ = value;
  // @@protoc_insertion_point(field_set:yproto.MNMap.channel)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ObjItem::kOnameFieldNumber;
const int ObjItem::kIdxFieldNumber;
const int ObjItem::kNumFacesFieldNumber;
const int ObjItem::kPosFieldNumber;
const int ObjItem::kBboxFieldNumber;
const int ObjItem::kXrefFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ObjItem::ObjItem()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yproto.ObjItem)
}

void ObjItem::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  pos_ = const_cast< ::yproto::Point3*>(&::yproto::Point3::default_instance());
  bbox_ = const_cast< ::yproto::Box3*>(&::yproto::Box3::default_instance());
}

ObjItem::ObjItem(const ObjItem& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yproto.ObjItem)
}

void ObjItem::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  oname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  idx_ = 0u;
  num_faces_ = 0;
  pos_ = NULL;
  bbox_ = NULL;
}

ObjItem::~ObjItem() {
  // @@protoc_insertion_point(destructor:yproto.ObjItem)
  SharedDtor();
}

void ObjItem::SharedDtor() {
  oname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete pos_;
    delete bbox_;
  }
}

void ObjItem::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ObjItem::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ObjItem_descriptor_;
}

const ObjItem& ObjItem::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ymax_2eproto();
  return *default_instance_;
}

ObjItem* ObjItem::default_instance_ = NULL;

ObjItem* ObjItem::New(::google::protobuf::Arena* arena) const {
  ObjItem* n = new ObjItem;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ObjItem::Clear() {
// @@protoc_insertion_point(message_clear_start:yproto.ObjItem)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(ObjItem, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<ObjItem*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(idx_, num_faces_);
  oname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && pos_ != NULL) delete pos_;
  pos_ = NULL;
  if (GetArenaNoVirtual() == NULL && bbox_ != NULL) delete bbox_;
  bbox_ = NULL;

#undef ZR_HELPER_
#undef ZR_

  xref_.Clear();
}

bool ObjItem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yproto.ObjItem)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string oname = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_oname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->oname().data(), this->oname().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "yproto.ObjItem.oname"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_idx;
        break;
      }

      // optional uint32 idx = 2;
      case 2: {
        if (tag == 16) {
         parse_idx:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &idx_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_num_faces;
        break;
      }

      // optional int32 num_faces = 3;
      case 3: {
        if (tag == 24) {
         parse_num_faces:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &num_faces_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_pos;
        break;
      }

      // optional .yproto.Point3 pos = 4;
      case 4: {
        if (tag == 34) {
         parse_pos:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_pos()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_bbox;
        break;
      }

      // optional .yproto.Box3 bbox = 5;
      case 5: {
        if (tag == 42) {
         parse_bbox:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_bbox()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_xref;
        break;
      }

      // repeated int32 xref = 6;
      case 6: {
        if (tag == 50) {
         parse_xref:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_xref())));
        } else if (tag == 48) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 50, input, this->mutable_xref())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yproto.ObjItem)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yproto.ObjItem)
  return false;
#undef DO_
}

void ObjItem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yproto.ObjItem)
  // optional string oname = 1;
  if (this->oname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->oname().data(), this->oname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "yproto.ObjItem.oname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->oname(), output);
  }

  // optional uint32 idx = 2;
  if (this->idx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->idx(), output);
  }

  // optional int32 num_faces = 3;
  if (this->num_faces() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->num_faces(), output);
  }

  // optional .yproto.Point3 pos = 4;
  if (this->has_pos()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->pos_, output);
  }

  // optional .yproto.Box3 bbox = 5;
  if (this->has_bbox()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->bbox_, output);
  }

  // repeated int32 xref = 6;
  if (this->xref_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(6, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_xref_cached_byte_size_);
  }
  for (int i = 0; i < this->xref_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->xref(i), output);
  }

  // @@protoc_insertion_point(serialize_end:yproto.ObjItem)
}

::google::protobuf::uint8* ObjItem::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:yproto.ObjItem)
  // optional string oname = 1;
  if (this->oname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->oname().data(), this->oname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "yproto.ObjItem.oname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->oname(), target);
  }

  // optional uint32 idx = 2;
  if (this->idx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->idx(), target);
  }

  // optional int32 num_faces = 3;
  if (this->num_faces() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->num_faces(), target);
  }

  // optional .yproto.Point3 pos = 4;
  if (this->has_pos()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->pos_, false, target);
  }

  // optional .yproto.Box3 bbox = 5;
  if (this->has_bbox()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *this->bbox_, false, target);
  }

  // repeated int32 xref = 6;
  if (this->xref_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      6,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _xref_cached_byte_size_, target);
  }
  for (int i = 0; i < this->xref_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->xref(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:yproto.ObjItem)
  return target;
}

int ObjItem::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yproto.ObjItem)
  int total_size = 0;

  // optional string oname = 1;
  if (this->oname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->oname());
  }

  // optional uint32 idx = 2;
  if (this->idx() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->idx());
  }

  // optional int32 num_faces = 3;
  if (this->num_faces() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->num_faces());
  }

  // optional .yproto.Point3 pos = 4;
  if (this->has_pos()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->pos_);
  }

  // optional .yproto.Box3 bbox = 5;
  if (this->has_bbox()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->bbox_);
  }

  // repeated int32 xref = 6;
  {
    int data_size = 0;
    for (int i = 0; i < this->xref_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->xref(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _xref_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ObjItem::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yproto.ObjItem)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ObjItem* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ObjItem>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yproto.ObjItem)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yproto.ObjItem)
    MergeFrom(*source);
  }
}

void ObjItem::MergeFrom(const ObjItem& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yproto.ObjItem)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  xref_.MergeFrom(from.xref_);
  if (from.oname().size() > 0) {

    oname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.oname_);
  }
  if (from.idx() != 0) {
    set_idx(from.idx());
  }
  if (from.num_faces() != 0) {
    set_num_faces(from.num_faces());
  }
  if (from.has_pos()) {
    mutable_pos()->::yproto::Point3::MergeFrom(from.pos());
  }
  if (from.has_bbox()) {
    mutable_bbox()->::yproto::Box3::MergeFrom(from.bbox());
  }
}

void ObjItem::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yproto.ObjItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObjItem::CopyFrom(const ObjItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yproto.ObjItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObjItem::IsInitialized() const {

  return true;
}

void ObjItem::Swap(ObjItem* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ObjItem::InternalSwap(ObjItem* other) {
  oname_.Swap(&other->oname_);
  std::swap(idx_, other->idx_);
  std::swap(num_faces_, other->num_faces_);
  std::swap(pos_, other->pos_);
  std::swap(bbox_, other->bbox_);
  xref_.UnsafeArenaSwap(&other->xref_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ObjItem::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ObjItem_descriptor_;
  metadata.reflection = ObjItem_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ObjItem

// optional string oname = 1;
void ObjItem::clear_oname() {
  oname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& ObjItem::oname() const {
  // @@protoc_insertion_point(field_get:yproto.ObjItem.oname)
  return oname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ObjItem::set_oname(const ::std::string& value) {
  
  oname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:yproto.ObjItem.oname)
}
 void ObjItem::set_oname(const char* value) {
  
  oname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:yproto.ObjItem.oname)
}
 void ObjItem::set_oname(const char* value, size_t size) {
  
  oname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:yproto.ObjItem.oname)
}
 ::std::string* ObjItem::mutable_oname() {
  
  // @@protoc_insertion_point(field_mutable:yproto.ObjItem.oname)
  return oname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ObjItem::release_oname() {
  // @@protoc_insertion_point(field_release:yproto.ObjItem.oname)
  
  return oname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ObjItem::set_allocated_oname(::std::string* oname) {
  if (oname != NULL) {
    
  } else {
    
  }
  oname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), oname);
  // @@protoc_insertion_point(field_set_allocated:yproto.ObjItem.oname)
}

// optional uint32 idx = 2;
void ObjItem::clear_idx() {
  idx_ = 0u;
}
 ::google::protobuf::uint32 ObjItem::idx() const {
  // @@protoc_insertion_point(field_get:yproto.ObjItem.idx)
  return idx_;
}
 void ObjItem::set_idx(::google::protobuf::uint32 value) {
  
  idx_ = value;
  // @@protoc_insertion_point(field_set:yproto.ObjItem.idx)
}

// optional int32 num_faces = 3;
void ObjItem::clear_num_faces() {
  num_faces_ = 0;
}
 ::google::protobuf::int32 ObjItem::num_faces() const {
  // @@protoc_insertion_point(field_get:yproto.ObjItem.num_faces)
  return num_faces_;
}
 void ObjItem::set_num_faces(::google::protobuf::int32 value) {
  
  num_faces_ = value;
  // @@protoc_insertion_point(field_set:yproto.ObjItem.num_faces)
}

// optional .yproto.Point3 pos = 4;
bool ObjItem::has_pos() const {
  return !_is_default_instance_ && pos_ != NULL;
}
void ObjItem::clear_pos() {
  if (GetArenaNoVirtual() == NULL && pos_ != NULL) delete pos_;
  pos_ = NULL;
}
const ::yproto::Point3& ObjItem::pos() const {
  // @@protoc_insertion_point(field_get:yproto.ObjItem.pos)
  return pos_ != NULL ? *pos_ : *default_instance_->pos_;
}
::yproto::Point3* ObjItem::mutable_pos() {
  
  if (pos_ == NULL) {
    pos_ = new ::yproto::Point3;
  }
  // @@protoc_insertion_point(field_mutable:yproto.ObjItem.pos)
  return pos_;
}
::yproto::Point3* ObjItem::release_pos() {
  // @@protoc_insertion_point(field_release:yproto.ObjItem.pos)
  
  ::yproto::Point3* temp = pos_;
  pos_ = NULL;
  return temp;
}
void ObjItem::set_allocated_pos(::yproto::Point3* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:yproto.ObjItem.pos)
}

// optional .yproto.Box3 bbox = 5;
bool ObjItem::has_bbox() const {
  return !_is_default_instance_ && bbox_ != NULL;
}
void ObjItem::clear_bbox() {
  if (GetArenaNoVirtual() == NULL && bbox_ != NULL) delete bbox_;
  bbox_ = NULL;
}
const ::yproto::Box3& ObjItem::bbox() const {
  // @@protoc_insertion_point(field_get:yproto.ObjItem.bbox)
  return bbox_ != NULL ? *bbox_ : *default_instance_->bbox_;
}
::yproto::Box3* ObjItem::mutable_bbox() {
  
  if (bbox_ == NULL) {
    bbox_ = new ::yproto::Box3;
  }
  // @@protoc_insertion_point(field_mutable:yproto.ObjItem.bbox)
  return bbox_;
}
::yproto::Box3* ObjItem::release_bbox() {
  // @@protoc_insertion_point(field_release:yproto.ObjItem.bbox)
  
  ::yproto::Box3* temp = bbox_;
  bbox_ = NULL;
  return temp;
}
void ObjItem::set_allocated_bbox(::yproto::Box3* bbox) {
  delete bbox_;
  bbox_ = bbox;
  if (bbox) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:yproto.ObjItem.bbox)
}

// repeated int32 xref = 6;
int ObjItem::xref_size() const {
  return xref_.size();
}
void ObjItem::clear_xref() {
  xref_.Clear();
}
 ::google::protobuf::int32 ObjItem::xref(int index) const {
  // @@protoc_insertion_point(field_get:yproto.ObjItem.xref)
  return xref_.Get(index);
}
 void ObjItem::set_xref(int index, ::google::protobuf::int32 value) {
  xref_.Set(index, value);
  // @@protoc_insertion_point(field_set:yproto.ObjItem.xref)
}
 void ObjItem::add_xref(::google::protobuf::int32 value) {
  xref_.Add(value);
  // @@protoc_insertion_point(field_add:yproto.ObjItem.xref)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ObjItem::xref() const {
  // @@protoc_insertion_point(field_list:yproto.ObjItem.xref)
  return xref_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ObjItem::mutable_xref() {
  // @@protoc_insertion_point(field_mutable_list:yproto.ObjItem.xref)
  return &xref_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ObjList::kObjsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ObjList::ObjList()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:yproto.ObjList)
}

void ObjList::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

ObjList::ObjList(const ObjList& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:yproto.ObjList)
}

void ObjList::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

ObjList::~ObjList() {
  // @@protoc_insertion_point(destructor:yproto.ObjList)
  SharedDtor();
}

void ObjList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ObjList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ObjList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ObjList_descriptor_;
}

const ObjList& ObjList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ymax_2eproto();
  return *default_instance_;
}

ObjList* ObjList::default_instance_ = NULL;

ObjList* ObjList::New(::google::protobuf::Arena* arena) const {
  ObjList* n = new ObjList;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ObjList::Clear() {
// @@protoc_insertion_point(message_clear_start:yproto.ObjList)
  objs_.Clear();
}

bool ObjList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:yproto.ObjList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .yproto.ObjItem objs = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_objs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_objs()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_objs;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:yproto.ObjList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:yproto.ObjList)
  return false;
#undef DO_
}

void ObjList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:yproto.ObjList)
  // repeated .yproto.ObjItem objs = 1;
  for (unsigned int i = 0, n = this->objs_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->objs(i), output);
  }

  // @@protoc_insertion_point(serialize_end:yproto.ObjList)
}

::google::protobuf::uint8* ObjList::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:yproto.ObjList)
  // repeated .yproto.ObjItem objs = 1;
  for (unsigned int i = 0, n = this->objs_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->objs(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:yproto.ObjList)
  return target;
}

int ObjList::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:yproto.ObjList)
  int total_size = 0;

  // repeated .yproto.ObjItem objs = 1;
  total_size += 1 * this->objs_size();
  for (int i = 0; i < this->objs_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->objs(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ObjList::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yproto.ObjList)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ObjList* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ObjList>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yproto.ObjList)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yproto.ObjList)
    MergeFrom(*source);
  }
}

void ObjList::MergeFrom(const ObjList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yproto.ObjList)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  objs_.MergeFrom(from.objs_);
}

void ObjList::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yproto.ObjList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObjList::CopyFrom(const ObjList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yproto.ObjList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObjList::IsInitialized() const {

  return true;
}

void ObjList::Swap(ObjList* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ObjList::InternalSwap(ObjList* other) {
  objs_.UnsafeArenaSwap(&other->objs_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ObjList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ObjList_descriptor_;
  metadata.reflection = ObjList_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ObjList

// repeated .yproto.ObjItem objs = 1;
int ObjList::objs_size() const {
  return objs_.size();
}
void ObjList::clear_objs() {
  objs_.Clear();
}
const ::yproto::ObjItem& ObjList::objs(int index) const {
  // @@protoc_insertion_point(field_get:yproto.ObjList.objs)
  return objs_.Get(index);
}
::yproto::ObjItem* ObjList::mutable_objs(int index) {
  // @@protoc_insertion_point(field_mutable:yproto.ObjList.objs)
  return objs_.Mutable(index);
}
::yproto::ObjItem* ObjList::add_objs() {
  // @@protoc_insertion_point(field_add:yproto.ObjList.objs)
  return objs_.Add();
}
::google::protobuf::RepeatedPtrField< ::yproto::ObjItem >*
ObjList::mutable_objs() {
  // @@protoc_insertion_point(field_mutable_list:yproto.ObjList.objs)
  return &objs_;
}
const ::google::protobuf::RepeatedPtrField< ::yproto::ObjItem >&
ObjList::objs() const {
  // @@protoc_insertion_point(field_list:yproto.ObjList.objs)
  return objs_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace yproto

// @@protoc_insertion_point(global_scope)
