// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yservice.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "yservice.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace y3d {

namespace protobuf_yservice_2eproto {


namespace {


}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = { ~0u };
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;
namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "yservice.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void TableStruct::Shutdown() {
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::y3d::protobuf_y3d_2eproto::InitDefaults();
  ::google::protobuf::protobuf_google_2fprotobuf_2fany_2eproto::InitDefaults();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\016yservice.proto\022\003y3d\032\ty3d.proto\032\031google"
      "/protobuf/any.proto2\225\n\n\020YServiceMaxTools"
      "\0224\n\014RenameObject\022\020.y3d.RenameParam\032\020.y3d"
      ".ResultReply\"\000\0225\n\013SaveProject\022\020.y3d.Proj"
      "ectInfo\032\022.y3d.ResponseEvent\"\000\022;\n\nNewProj"
      "ect\022\024.y3d.NewProjectParam\032\025.y3d.Response"
      "NProject\"\000\0228\n\013LoadProject\022\020.y3d.ProjectI"
      "nfo\032\025.y3d.ResponseNProject\"\000\022:\n\rDeletePr"
      "oject\022\020.y3d.ProjectInfo\032\025.y3d.ResponseNP"
      "roject\"\000\022*\n\006Unwrap\022\014.y3d.EUnwrap\032\020.y3d.R"
      "esultReply\"\000\022,\n\007Packing\022\r.y3d.EPacking\032\020"
      ".y3d.ResultReply\"\000\022,\n\007LowPoly\022\r.y3d.ELow"
      "poly\032\020.y3d.ResultReply\"\000\022-\n\nLoadSystem\022\017"
      ".y3d.EmptyParam\032\014.y3d.YSystem\"\000\022.\n\nSaveS"
      "ystem\022\014.y3d.YSystem\032\020.y3d.ResultReply\"\000\022"
      ".\n\nBakeNormal\022\014.y3d.ENormal\032\020.y3d.Result"
      "Reply\"\000\0221\n\rBakeNormalMax\022\014.y3d.ENormal\032\020"
      ".y3d.ResultReply\"\000\0228\n\rMakeNode4Edit\022\023.y3"
      "d.Make4TestParam\032\020.y3d.ResultReply\"\000\022<\n\r"
      "BatchOptimize\022\027.y3d.BatchOptimizeParam\032\020"
      ".y3d.ResultReply\"\000\022.\n\010TestTest\022\016.y3d.Tes"
      "tParam\032\020.y3d.ResultReply\"\000\0225\n\020GetObjectF"
      "romMax\022\017.y3d.EmptyParam\032\016.y3d.YAreaList\""
      "\000\0222\n\013CloneObject\022\017.y3d.EmptyParam\032\020.y3d."
      "ResultReply\"\000\0223\n\016DoStreamClient\022\013.y3d.YE"
      "vent\032\022.y3d.ResponseEvent(\001\0220\n\016DoStreamSe"
      "rver\022\017.y3d.EmptyParam\032\013.y3d.YEvent0\001\022(\n\010"
      "DoAction\022\013.y3d.YEvent\032\013.y3d.YEvent(\0010\001\022*"
      "\n\007DoEvent\022\013.y3d.YEvent\032\022.y3d.ResponseEve"
      "nt\022,\n\010DoUnwrap\022\014.y3d.EUnwrap\032\022.y3d.Respo"
      "nseEvent\022/\n\010Shutdown\022\017.y3d.EmptyParam\032\020."
      "y3d.ResultReply\"\000\0222\n\rAddTestObject\022\017.y3d"
      ".TestOParam\032\020.y3d.ResultReply\0224\n\017ApplyTe"
      "stObject\022\017.y3d.TestOParam\032\020.y3d.ResultRe"
      "ply2j\n\014YServiceTest\022,\n\006MTest1\022\017.y3d.Empt"
      "yParam\032\017.y3d.EmptyParam\"\000\022,\n\006MTest2\022\017.y3"
      "d.EmptyParam\032\017.y3d.EmptyParam\"\0002\316\005\n\016YSer"
      "viceMaster\0229\n\nAllWorkers\022\023.y3d.AllWorker"
      "Param\032\024.y3d.YWorkerResponse\"\000\0225\n\016StopAll"
      "Workers\022\017.y3d.EmptyParam\032\020.y3d.ResultRep"
      "ly\"\000\0228\n\tAddWorker\022\023.y3d.YWorkerRequest\032\024"
      ".y3d.YWorkerResponse\"\000\0226\n\016CloseWorkerApp"
      "\022\020.y3d.WorkerParam\032\020.y3d.ResultReply\"\000\0227"
      "\n\013StartWorker\022\020.y3d.WorkerParam\032\024.y3d.YW"
      "orkerResponse\"\000\0226\n\nStopWorker\022\020.y3d.Work"
      "erParam\032\024.y3d.YWorkerResponse\"\000\0227\n\017AppEx"
      "itCallback\022\020.y3d.WorkerParam\032\020.y3d.Resul"
      "tReply\"\000\0221\n\020ShowJobInMachine\022\014.y3d.YWork"
      "er\032\r.y3d.YJobList\"\000\0222\n\013CheckHealth\022\017.y3d"
      ".EmptyParam\032\020.y3d.ResultReply\"\000\0226\n\022Updat"
      "eWorkerStatus\022\014.y3d.YWorker\032\020.y3d.Result"
      "Reply\"\000\022-\n\nLoadSystem\022\017.y3d.EmptyParam\032\014"
      ".y3d.YSystem\"\000\022.\n\nSaveSystem\022\014.y3d.YSyst"
      "em\032\020.y3d.ResultReply\"\000\0220\n\rGiveMeAWorker\022"
      "\017.y3d.EmptyParam\032\014.y3d.YWorker\"\0002s\n\022YSer"
      "viceMainWorker\022*\n\007DoEvent\022\013.y3d.YEvent\032\022"
      ".y3d.ResponseEvent\0221\n\016CloseWorkerApp\022\013.y"
      "3d.YEvent\032\022.y3d.ResponseEventB\010\252\002\005y3d.sb"
      "\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 2327);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "yservice.proto", &protobuf_RegisterTypes);
  ::y3d::protobuf_y3d_2eproto::AddDescriptors();
  ::google::protobuf::protobuf_google_2fprotobuf_2fany_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_yservice_2eproto


// @@protoc_insertion_point(namespace_scope)

}  // namespace y3d

// @@protoc_insertion_point(global_scope)
